Language = {
    open = "Open clothing bag",
    pickup = "Pick up clothing bag",
    placing = "Placing the clothing bag...",
    picking = "Picking up the clothing bag...",
    noitem = "You don't have a clothing bag.",
    nooutfit = "You don't have any outfit in the bag.",
    wearing = "You are currently putting on the outfit...",
    maxoutfits = "You have saved the maximum number of outfits.",
    save = "Save",
    savedoutfit = "Outfit saved as:",
    saveoutfit = "Save outfit",
    savenowoutfit = "Save current outfit",
    outfitname = "Outfit name",
    myoutfit = "My Outfit",
    outfiton = "The outfit is now on you",
    nooutfits = "You have no saved outfits.",
    moreoptions = "Click for more options",
    outfits = "Outfits",
    showsavedoutfits = "Show saved outfits",
    dressup = "Dress up",
    rename = "Rename",
    renameoutfit = "Rename outfit",
    renameoutfitname = "New outfit name",
    delete = "Delete",
    title = "Outfit Bag",
    placeditem = "You have successfully placed the bag of clothes.",
}


--[[ Czech Language
Language = {
    open = "Otevřít tašku s oblečením",
    pickup = "Vzít tašku s oblečením",
    placing = "Pokládání tašky s oblečením...",
    picking = "Braní tašky s oblečením...",
    noitem = "Nemáš u sebe tašku s oblečením.",
    nooutfit = "Nemáš žádný outfit v tašce.",
    wearing = "Momentálně si oblékáš outfit...",
    maxoutfits = "Máš uložený maximální počet outfitů.",
    save = "Uložit",
    savedoutfit = "Outfit uložen jako:",
    saveoutfit = "Uložit outfit",
    savenowoutfit = "Uloží aktuální outfit",
    outfitname = "Název outfitu",
    myoutfit = "Můj Outfit",
    outfiton = "Outfit je nyní na tobě",
    nooutfits = "Nemáš žádný outfit uložený.",
    moreoptions = "Klikni pro více možností",
    outfits = "Outfity",
    showsavedoutfits = "Zobrazit uložené outfity",
    dressup = "Obléknout se",
    rename = "Přejmenovat",
    renameoutfit = "Přejmenovat outfit",
    renameoutfitname = "Nový název outfitu",
    delete = "Smazat",
    title = "Taška s oblečením",
    placeditem = "Úspěšně jsi položil tašku s oblečením.",
}


]]